spring:
  application:
    name: foodiesapi

# MongoDB configuration
  mongodb:
    uri: ${MONGODB_URI}

# AWS Configuration
aws:
  access:
    key: ${AWS_ACCESS_KEY_ID}
  secret:
    key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION_NAME}
  s3:
    bucket: ${S3_BUCKET_NAME}

jwt.secret.key: ${JWT_SECRET_KEY}

# Razorpay Configuration
razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}

server:
  port: ${PORT:8080}
