spring:
  application:
    name: foodiesapi

# MongoDB configuration
  mongodb:
#    uri: ${MONGODB_URI}
    uri: mongodb+srv://foodiesUN:foodiesUN@cluster0.hbk79vd.mongodb.net/Cluster0?appName=Cluster0

aws:
  access:
    key: ${AWS_ACCESS_KEY_ID}
  secret:
    key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION_NAME}
  s3:
    bucket: ${S3_BUCKET_NAME}
